[tool.poetry]
name = "ai_daily"
version = "0.1.0"
description = "ai_daily"
authors = [
    "langchain-ai"
]
packages = [
    { include = "ai_daily" },
]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langgraph = "^0.2.0"
langchain_anthropic = "^0.1.0"
langchain_core = "^0.2.0"
langchain_openai = "^0.1.0"
tavily-python = "^0.3.0"
langchain_community = "^0.2.0"
openpyxl = "^3.1.5"
pandas = "^2.2.3"
jinja2 = "^3.1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"